## all of the instances currently in Courtlistener as of 6/2016, taken from: https://www.courtlistener.com/api/jurisdictions/
full_names = {'scotus':'Supreme Court of the United States',
'ca1':'Court of Appeals for the First Circuit',
'ca2':'Court of Appeals for the Second Circuit',
'ca3':'Court of Appeals for the Third Circuit',
'ca4':'Court of Appeals for the Fourth Circuit',
'ca5':'Court of Appeals for the Fifth Circuit',
'ca6':'Court of Appeals for the Sixth Circuit',
'ca7':'Court of Appeals for the Seventh Circuit',
'ca8':'Court of Appeals for the Eighth Circuit',
'ca9':'Court of Appeals for the Ninth Circuit',
'ca10':'Court of Appeals for the Tenth Circuit',
'ca11':'Court of Appeals for the Eleventh Circuit',
'cadc':'Court of Appeals for the D.C. Circuit',
'cafc':'Court of Appeals for the Federal Circuit',
'caca':'Circuit Court for California',
'afcca':'United States Air Force Court of Criminal Appeals',
'asbca':'Armed Services Board of Contract Appeals',
'armfor':'Court of Appeals for the Armed Forces',
'acca':'Army Court of Criminal Appeals',
'cc':'United States Court of Claims',
'uscfc':'United States Court of Federal Claims',
'com':'Commerce Court',
'ccpa':'Court of Customs and Patent Appeals',
'cusc':'United States Customs Court',
'tax':'United States Tax Court',
'mc':'United States Court of Military Commission Review',
'mspb':'Merit Systems Protection Board',
'nmcca':'Navy-Marine Corps Court of Criminal Appeals',
'cavc':'United States Court of Appeals for Veterans Claims',
'bva':'Board of Veterans\' Appeals',
'eca':'Emergency Court of Appeals',
'tecoa':'Temporary Emergency Court of Appeals',
'fiscr':'Foreign Intelligence Surveillance Court of Review',
'fisc':'Foreign Intelligence Surveillance Court',
'reglrailreorgct':'Special Court under the Regional Rail Reorganization Act',
'cit':'United States Court of International Trade',
'bap1':'Bankruptcy Appellate Panel of the First Circuit',
'bap2':'Bankruptcy Appellate Panel of the Second Circuit',
'bap6':'Bankruptcy Appellate Panel of the Sixth Circuit',
'bap8':'United States Bankruptcy Appellate Panel for the Eighth Circuit',
'bap9':'United States Bankruptcy Appellate Panel for the Ninth Circuit',
'bap10':'Bankruptcy Appellate Panel of the Tenth Circuit',
'bapme':'Bankruptcy Appellate Panel, D. Maine',
'bapma':'Bankruptcy Appellate Panel of Massachusetts',
'almb':'United States Bankruptcy Court, M.D. Alabama',
'alnb':'United States Bankruptcy Court, N.D. Alabama',
'alsb':'United States Bankruptcy Court, S.D. Alabama',
'akb':'United States Bankruptcy Court, D. Alaska',
'arb':'United States Bankruptcy Court, D. Arizona',
'areb':'United States Bankruptcy Court, E.D. Arkansas',
'arwb':'United States Bankruptcy Court, W.D. Arkansas',
'cacb':'United States Bankruptcy Court, C.D. California',
'caeb':'United States Bankruptcy Court, E.D. California',
'canb':'United States Bankruptcy Court, N.D. California',
'casb':'United States Bankruptcy Court, S.D. California',
'cob':'United States Bankruptcy Court, D. Colorado',
'ctb':'United States Bankruptcy Court, D. Connecticut',
'deb':'United States Bankruptcy Court, D. Delaware',
'dcb':'United States Bankruptcy Court, District of Columbia',
'flmb':'United States Bankruptcy Court, M.D. Florida',
'flnb':'United States Bankruptcy Court, N.D. Florida',
'flsb':'United States Bankruptcy Court, S.D. Florida.',
'gamb':'United States Bankruptcy Court, M.D. Georgia',
'ganb':'United States Bankruptcy Court, N.D. Georgia',
'gasb':'United States Bankruptcy Court, S.D. Georgia',
'hib':'United States Bankruptcy Court, D. Hawaii',
'idb':'United States Bankruptcy Court, D. Idaho',
'ilcb':'United States Bankruptcy Court, C.D. Illinois',
'ilnb':'United States Bankruptcy Court, N.D. Illinois',
'ilsb':'United States Bankruptcy Court, S.D. Illinois',
'innb':'United States Bankruptcy Court, N.D. Indiana',
'insb':'United States Bankruptcy Court, S.D. Indiana',
'ianb':'United States Bankruptcy Court, N.D. Iowa',
'iasb':'United States Bankruptcy Court, S.D. Iowa',
'ksb':'United States Bankruptcy Court, D. Kansas',
'kyeb':'United States Bankruptcy Court, E.D. Kentucky',
'kywb':'United States Bankruptcy Court, W.D. Kentucky',
'laeb':'United States Bankruptcy Court, E.D. Louisiana',
'lamb':'United States Bankruptcy Court, M.D. Louisiana',
'lawb':'United States Bankruptcy Court, W.D. Louisiana',
'meb':'United States Bankruptcy Court, D. Maine',
'mdb':'United States Bankruptcy Court, D. Maryland',
'mab':'United States Bankruptcy Court, D. Massachusetts',
'mieb':'United States Bankruptcy Court, E.D. Michigan',
'miwb':'United States Bankruptcy Court, W.D. Michigan',
'mnb':'United States Bankruptcy Court, D. Minnesota',
'msnb':'United States Bankruptcy Court, N.D. Mississippi',
'mssb':'United States Bankruptcy Court, S.D. Mississippi',
'moeb':'United States Bankruptcy Court, E.D. Missouri',
'mowb':'United States Bankruptcy Court, W.D. Missouri',
'mtb':'United States Bankruptcy Court, D. Montana',
'nebraskab':'United States Bankruptcy Court, D. Nebraska',
'nvb':'United States Bankruptcy Court, D. Nevada',
'nhb':'United States Bankruptcy Court, D. New Hampshire',
'njb':'United States Bankruptcy Court, D. New Jersey',
'nmb':'United States Bankruptcy Court, D. New Mexico',
'nyeb':'United States Bankruptcy Court, E.D. New York',
'nynb':'United States Bankruptcy Court, N.D. New York',
'nysb':'United States Bankruptcy Court, S.D. New York',
'nywb':'United States Bankruptcy Court, W.D. New York',
'nceb':'United States Bankruptcy Court, E.D. North Carolina',
'ncmb':'United States Bankruptcy Court, M.D. North Carolina',
'ncwb':'United States Bankruptcy Court, W.D. North Carolina',
'ndb':'United States Bankruptcy Court, D. North Dakota',
'ohnb':'United States Bankruptcy Court, N.D. Ohio',
'ohsb':'United States Bankruptcy Court, S.D. Ohio',
'okeb':'United States Bankruptcy Court, E.D. Oklahoma',
'oknb':'United States Bankruptcy Court, N.D. Oklahoma',
'okwb':'United States Bankruptcy Court, W.D. Oklahoma',
'orb':'United States Bankruptcy Court, D. Oregon',
'paeb':'United States Bankruptcy Court, E.D. Pennsylvania',
'pamb':'United States Bankruptcy Court, M.D. Pennsylvania',
'pawb':'United States Bankruptcy Court, W.D. Pennsylvania',
'rib':'United States Bankruptcy Court, D. Rhode Island',
'scb':'United States Bankruptcy Court, D. South Carolina',
'sdb':'United States Bankruptcy Court, D. South Dakota',
'tneb':'United States Bankruptcy Court, E.D. Tennessee',
'tnmb':'United States Bankruptcy Court, M.D. Tennessee',
'tnwb':'United States Bankruptcy Court, W.D. Tennessee',
'tennesseeb':'United States Bankruptcy Court, D. Tennessee',
'txeb':'United States Bankruptcy Court, E.D. Texas',
'txnb':'United States Bankruptcy Court, N.D. Texas',
'txsb':'United States Bankruptcy Court, S.D. Texas',
'txwb':'United States District Court, W.D. Texas',
'utb':'United States Bankruptcy Court, D. Utah',
'vtb':'United States Bankruptcy Court, D. Vermont',
'vaeb':'United States Bankruptcy Court, E.D. Virginia',
'vawb':'United States Bankruptcy Court, W.D. Virginia',
'waeb':'United States Bankruptcy Court, E.D. Washington',
'wawb':'United States Bankruptcy Court, W.D. Washington',
'wvnb':'United States District Court, N.D. West Virginia',
'wvsb':'United States Bankruptcy Court, S.D. West Virginia',
'wieb':'United States Bankruptcy Court, E.D. Wisconsin',
'wiwb':'United States Bankruptcy Court, W.D. Wisconsin',
'wyb':'United States Bankruptcy Court, D. Wyoming',
'gub':'United States Bankruptcy Court, D. Guam',
'nmib':'United States Bankruptcy Court, Northern Mariana Islands',
'prb':'United States Bankruptcy Court, D. Puerto Rico',
'vib':'United States Bankruptcy Court, D. Virgin Islands',
'dcd':'District Court, District of Columbia',
'ald':'District Court, D. Alabama',
'almd':'District Court, M.D. Alabama',
'alnd':'District Court, N.D. Alabama',
'alsd':'District Court, S.D. Alabama',
'akd':'District Court, D. Alaska',
'azd':'District Court, D. Arizona',
'ared':'District Court, E.D. Arkansas',
'arwd':'District Court, W.D. Arkansas',
'californiad':'District Court, D. California',
'cacd':'District Court, C.D. California',
'caed':'District Court, E.D. California',
'cand':'District Court, N.D. California',
'casd':'District Court, S.D. California',
'cod':'District Court, D. Colorado',
'ctd':'District Court, D. Connecticut',
'ded':'District Court, D. Delaware',
'fld':'District Court, D. Florida',
'flmd':'District Court, M.D. Florida',
'flnd':'District Court, N.D. Florida',
'flsd':'District Court, S.D. Florida',
'gad':'District Court, D. Georgia',
'gamd':'District Court, M.D. Georgia',
'gand':'District Court, N.D. Georgia',
'gasd':'District Court, S.D. Georgia',
'hid':'District Court, D. Hawaii',
'idd':'District Court, D. Idaho',
'ilcd':'District Court, C.D. Illinois',
'ilnd':'District Court, N.D. Illinois',
'ilsd':'District Court, S.D. Illinois',
'illinoised':'District Court, E.D. Illinois',
'illinoisd':'District Court, D. Illinois',
'innd':'District Court, N.D. Indiana',
'insd':'District Court, S.D. Indiana',
'indianad':'District Court, D. Indiana',
'iad':'District Court, D. Iowa',
'iand':'District Court, N.D. Iowa',
'iasd':'District Court, S.D. Iowa',
'ksd':'District Court, D. Kansas',
'kyd':'District Court, D. Kentucky',
'kyed':'District Court, E.D. Kentucky',
'kywd':'District Court, W.D. Kentucky',
'lad':'District Court, D. Louisiana',
'laed':'District Court, E.D. Louisiana.',
'lamd':'District Court, M.D. Louisiana',
'lawd':'District Court, W.D. Louisiana',
'orld':'District Court, Orleans',
'med':'District Court, D. Maine',
'mdd':'District Court, D. Maryland',
'mad':'District Court, D. Massachusetts',
'michd':'District Court, D. Michigan',
'mied':'District Court, E.D. Michigan',
'miwd':'District Court, W.D. Michigan',
'mnd':'District Court, D. Minnesota',
'missd':'District Court, D. Mississippi',
'msnd':'District Court, N.D. Mississippi',
'mssd':'District Court, S.D. Mississippi',
'mod':'District Court, D. Missouri',
'mocd':'District Court, C.D. Missouri',
'moed':'District Court, E.D. Missouri',
'mowd':'District Court, W.D. Missouri',
'mosd':'District Court, S.D. Missouri',
'mtd':'District Court, D. Montana',
'ned':'District Court, D. Nebraska',
'nvd':'District Court, D. Nevada',
'nhd':'District Court, D. New Hampshire',
'njd':'District Court, D. New Jersey',
'nmd':'District Court, D. New Mexico',
'nyd':'District Court, D. New York',
'nyed':'District Court, E.D. New York',
'nynd':'District Court, N.D. New York',
'nysd':'District Court, S.D. New York',
'nywd':'District Court, W.D. New York',
'nced':'District Court, E.D. North Carolina',
'ncmd':'District Court, M.D. North Carolina',
'ncwd':'District Court, W.D. North Carolina',
'ndd':'District Court, D. North Dakota',
'ncd':'District Court, D. North Carolina',
'ohnd':'District Court, N.D. Ohio',
'ohsd':'District Court, S.D. Ohio',
'ohiod':'District Court, D. Ohio',
'oked':'District Court, E.D. Oklahoma',
'oknd':'District Court, N.D. Oklahoma',
'okwd':'District Court, W.D. Oklahoma',
'ord':'District Court, D. Oregon',
'paed':'District Court, E.D. Pennsylvania',
'pamd':'District Court, M.D. Pennsylvania',
'pawd':'District Court, W.D. Pennsylvania',
'pennsylvaniad':'District Court, D. Pennsylvania',
'rid':'District Court, D. Rhode Island',
'scd':'United States District Court, D. South Carolina',
'southcarolinaed':'District Court, E.D. South Carolina',
'southcarolinawd':'District Court, W.D. South Carolina',
'sdd':'District Court, D. South Dakota',
'tned':'District Court, E.D. Tennessee',
'tnmd':'District Court, M.D. Tennessee',
'tnwd':'District Court, W.D. Tennessee',
'tennessed':'District Court, D. Tennessee',
'texd':'District Court, D. Texas',
'txed':'District Court, E.D. Texas',
'txnd':'District Court, N.D. Texas',
'txsd':'District Court, S.D. Texas',
'txwd':'District Court, W.D. Texas',
'utd':'United States District Court, D. Utah',
'vtd':'District Court, D. Vermont',
'vad':'District Court, D. Virginia',
'vaed':'District Court, E.D. Virginia',
'vawd':'District Court, W.D. Virginia',
'washd':'District Court, D. Washington',
'waed':'District Court, E.D. Washington',
'wawd':'District Court, W.D. Washington',
'wvad':'District Court, D. West Virginia',
'wvnd':'District Court, N.D. West Virginia',
'wvsd':'District Court, S.D. West Virginia.',
'wisd':'District Court, D. Wisconsin',
'wied':'District Court, E.D. Wisconsin',
'wiwd':'District Court, W.D. Wisconsin',
'wyd':'District Court, D. Wyoming',
'canalzoned':'District Court, Canal Zone',
'gud':'District Court, D. Guam',
'nmid':'District Court, Northern Mariana Islands',
'prd':'District Court, D. Puerto Rico',
'vid':'District Court, Virgin Islands',
'ala':'Supreme Court of Alabama',
'alactapp':'Alabama Court of Appeals',
'alacrimapp':'Court of Criminal Appeals of Alabama',
'alacivapp':'Court of Civil Appeals of Alabama',
'alaska':'Alaska Supreme Court',
'alaskactapp':'Court of Appeals of Alaska',
'ariz':'Arizona Supreme Court',
'arizctapp':'Court of Appeals of Arizona',
'ariztaxct':'Arizona Tax Court',
'ark':'Supreme Court of Arkansas',
'arkctapp':'Court of Appeals of Arkansas',
'cal':'California Supreme Court',
'calctapp':'California Court of Appeal',
'colo':'Supreme Court of Colorado',
'coloctapp':'Colorado Court of Appeals',
'conn':'Supreme Court of Connecticut',
'connappct':'Connecticut Appellate Court',
'connsuperct':'Connecticut Superior Court',
'del':'Supreme Court of Delaware',
'delch':'Court of Chancery of Delaware',
'delsuperct':'Superior Court of Delaware',
'delctcompl':'Delaware Court of Common Pleas',
'delfamct':'Delaware Family Court',
'deljudct':'Court on the Judiciary of Delaware.',
'dc':'District of Columbia Court of Appeals',
'fla':'Supreme Court of Florida',
'fladistctapp':'District Court of Appeal of Florida',
'ga':'Supreme Court of Georgia',
'gactapp':'Court of Appeals of Georgia.',
'haw':'Hawaii Supreme Court',
'hawapp':'Hawaii Intermediate Court of Appeals',
'idaho':'Idaho Supreme Court',
'idahoctapp':'Idaho Court of Appeals',
'ill':'Illinois Supreme Court',
'illappct':'Appellate Court of Illinois',
'ind':'Indiana Supreme Court',
'indctapp':'Indiana Court of Appeals',
'indtc':'Indiana Tax Court',
'iowa':'Supreme Court of Iowa',
'iowactapp':'Court of Appeals of Iowa',
'kan':'Supreme Court of Kansas',
'kanctapp':'Court of Appeals of Kansas',
'ky':'Kentucky Supreme Court',
'kyctapp':'Court of Appeals of Kentucky',
'la':'Supreme Court of Louisiana',
'lactapp':'Louisiana Court of Appeal',
'me':'Supreme Judicial Court of Maine',
'md':'Court of Appeals of Maryland',
'mdctspecapp':'Court of Special Appeals of Maryland',
'mass':'Massachusetts Supreme Judicial Court',
'massappct':'Massachusetts Appeals Court',
'masssuperct':'Massachusetts Superior Court',
'massdistct':'Massachusetts District Court',
'mich':'Michigan Supreme Court',
'michctapp':'Michigan Court of Appeals',
'minn':'Supreme Court of Minnesota',
'minnctapp':'Court of Appeals of Minnesota',
'miss':'Mississippi Supreme Court',
'missctapp':'Court of Appeals of Mississippi',
'mo':'Supreme Court of Missouri',
'moctapp':'Missouri Court of Appeals',
'mont':'Montana Supreme Court',
'neb':'Nebraska Supreme Court',
'nebctapp':'Nebraska Court of Appeals',
'nev':'Nevada Supreme Court',
'nh':'Supreme Court of New Hampshire',
'nj':'Supreme Court of New Jersey',
'njsuperctappdiv':'New Jersey Superior Court',
'njtaxct':'New Jersey Tax Court',
'nm':'New Mexico Supreme Court',
'nmctapp':'New Mexico Court of Appeals',
'ny':'New York Court of Appeals',
'nyappdiv':'Appellate Division of the Supreme Court of the State of New York',
'nyappterm':'Appellate Terms of the Supreme Court of New York',
'nysupct':'New York Supreme Court',
'nyfamct':'New York Family Court',
'nysurct':'New York Surrogate\'s Court',
'nc':'Supreme Court of North Carolina',
'ncctapp':'Court of Appeals of North Carolina',
'nd':'North Dakota Supreme Court',
'ndctapp':'North Dakota Court of Appeals',
'ohio':'Ohio Supreme Court',
'ohioctapp':'Ohio Court of Appeals',
'ohioctcl':'Ohio Court of Claims',
'okla':'Supreme Court of Oklahoma',
'oklacivapp':'Court of Civil Appeals of Oklahoma',
'oklacrimapp':'Court of Criminal Appeals of Oklahoma',
'oklajeap':'Oklahoma Judicial Ethics Advisory Panel',
'oklacoj':'Court on the Judiciary of Oklahoma',
'oklaag':'Oklahoma Attorney General Reports',
'or':'Oregon Supreme Court',
'orctapp':'Court of Appeals of Oregon',
'pa':'Supreme Court of Pennsylvania',
'pasuperct':'Superior Court of Pennsylvania',
'pacommwct':'Commonwealth Court of Pennsylvania',
'cjdpa':'Court of Judicial Discipline of Pennsylvania',
'ri':'Supreme Court of Rhode Island',
'sc':'Supreme Court of South Carolina',
'scctapp':'Court of Appeals of South Carolina',
'sd':'South Dakota Supreme Court',
'tenn':'Tennessee Supreme Court',
'tennctapp':'Court of Appeals of Tennessee',
'tenncrimapp':'Court of Criminal Appeals of Tennessee',
'tex':'Texas Supreme Court',
'texapp':'Court of Appeals of Texas',
'texcrimapp':'Court of Criminal Appeals of Texas',
'texreview':'Texas Special Court of Review',
'utah':'Utah Supreme Court',
'utahctapp':'Court of Appeals of Utah',
'vt':'Supreme Court of Vermont',
'va':'Supreme Court of Virginia',
'vactapp':'Court of Appeals of Virginia',
'wash':'Washington Supreme Court',
'washctapp':'Court of Appeals of Washington',
'wva':'West Virginia Supreme Court',
'wis':'Wisconsin Supreme Court',
'wisctapp':'Court of Appeals of Wisconsin',
'wyo':'Wyoming Supreme Court',
'usjc':'United States Judicial Conference Committee',
'jpml':'United States Judicial Panel on Multidistrict Litigation',
'stp':'United States Special Tribunal of Pennsylvania'
}
